#! /bin/bash

for graph_type in geant abilene dtelekom erdos_renyi balanced_tree hypercube star grid_2d small_world
do
    for change in learner source rate
    do
        sbatch ../script.sh plot_sens.py --graph_type $graph_type --change $change
    done
done


for graph_type in geant abilene dtelekom erdos_renyi balanced_tree hypercube star grid_2d small_world
do
    sbatch ../script.sh plot_stepsize.py --graph_type $graph_type
done