#! /bin/bash

#for graph_type in geant abilene dtelekom
#do
#    sbatch ../script.sh distributedSolver.py --graph_type $graph_type
#done

for graph_type in erdos_renyi balanced_tree hypercube star grid_2d small_world
do
    sbatch ../script.sh distributedSolver.py --graph_type $graph_type
done